### ISSUE TITLE
Support documentation of validator functions in Swagger

### ISSUE THREAD

**Issue by apryor6** [apryor6/flask_accepts#16]
See some preliminary discussion in #15 

Marshmallow provides rich validation that, although it can be used in flask_accepts now, does not come with documentation. We can create a mapping to provide Swagger docs on validators that have a corresponding validator in both libraries. The remainder will either get ignored or can be addressed with a lower level solution.

**Comment by apryor6** [comment]
Actually, it does not appear that RESTplus documents validators in Swagger. If that is the case, the existing functionality should be sufficient as you are getting the improved error messaging/validation from Marshmallow while also maintaining the equivalent level of documentation. 

@flayman if you disagree feel free to reopen for discussion.

**Comment by flayman** [comment]
Hi. Sorry, it's been a long weekend here. There are validators on the one hand, and constraints on the other. Marshmallow deals seems to deal with all constraints through validators. Flask-restplus and Swagger use json schema, which has constraints you see as dictionary properties. For example:

```
...
    "definitions": {
        "MySchema": {
            "type": "object",
            "properties": {
                "createdBy": {
                    "type": "integer",
                    "format": "int32"
                },
                "name": {
                    "type": "string",
                    "maxLength": 25
                },
                "description": {
                    "type": "string",
                    "x-nullable": true
                }
            },
            "required": [
                "name"
            ]
        },
...
```

The maxLength property there will cause Swagger to reject input longer than 25 characters with a response like:

```
{
  "errors": {
    "name": "'asdfasdfasdfasdfasdfasdfasdgsdgasdfherfjhsdf hdfhsdfhsd fh sdfh sdfh sdfhsd fhs dfhsd f hsdfh sdfh sdfh sdfh' is too long"
  },
  "message": "Input payload validation failed"
}
```

This is not such an issue, as you say, because Marshmallow will reject it and you just pass the error back in the response. However, this is more consistent and it's a safety valve. It seems to me that you need to try to build the swagger.json to be correct since it is the description of the API. There are other advantages, such as that some clients may be able to do client side validation. The constraints are not part of the documentation, but the example values that are generated will make use of default values. That's very handy.

**Comment by flayman** [comment]
I don't really know. It would be useful to invite comment from the flask-restplus maintainers. To be clear, I'm not one. This is probably really more of a pure Swagger thing. The maintainers will be better able to comment on completeness. I feel confident in saying that support for a lot more of the types will be needed though.

**Comment by flayman** [comment]
By the way, good work on all of this. It's looking good. The code is well structured and you're very quick to put out releases.
