### ISSUE TITLE
Support for different swagger output per HTTP method

### ISSUE THREAD

**Issue by shawalli** [apryor6/flask_accepts#26]
Say I have the following snippet:
```python
class WidgetSchema(Schema):
    id = fields.UUID()
    created_at = fields.DateTime()
    foo = fields.String()
    baz = fields.Integer()


def create_app():
    app = Flask(__name__)
    api = Api(app)

    @api.route("/widget")
    class WidgetResource(Resource):
        @accepts(schema=WidgetSchema, api=api)
        @responds(schema=WidgetSchema, api=api)
        def post(self):
            # save data to a new record, and return ID
            return request.parsed_obj

        @accepts(dict(name="id", type=UUID), schema=WidgetSchema, api=api)
        @responds(schema=WidgetSchema, api=api)
        def patch(self):
            return request.parsed_obj

    return app
```

In this scenario, here are the available fields for each method:
`post`
- foo
- baz

`patch`
- foo

`id` and `created_at` are set by the database, and `baz` may only be set during a record creation. Therefore, the model (which describes Widget records), and the acceptable fields for each method are all different.

The default behavior should remain the same. However, the introduction of a new parameter (`fields` or something) could provide a list of strings. The strings would be the field names that are allowed for a particular method. If provided, the decorator should ensure that only the fields from that list are included in the request. Additionally, the Swagger UI would only list fields from `fields` as available inputs.

The only alternative solution I can see is to create a separate schema for each unique method accept and response (which could become quite verbose).

Here is an example of the same snippet with the new parameters:
```python
class WidgetSchema(Schema):
    id = fields.UUID()
    created_at = fields.DateTime()
    foo = fields.String()
    baz = fields.Integer()


def create_app():
    app = Flask(__name__)
    api = Api(app)

    @api.route("/widget")
    class WidgetResource(Resource):
        @accepts(schema=WidgetSchema, api=api, fields=["foo", "baz"])
        @responds(schema=WidgetSchema, api=api)
        def post(self):
            # save data to a new record, and return ID
            return request.parsed_obj

        @accepts(dict(name="id", type=UUID), schema=WidgetSchema, api=api, fields=["foo"])
        @responds(schema=WidgetSchema, api=api)
        def patch(self):
            return request.parsed_obj

    return app
```

**Comment by apryor6** [comment]
You can actually accomplish what you want by creating an _instance_ of your schema and using the `only` and `exclude` parameters. See [this example I just added](https://github.com/apryor6/flask_accepts/blob/master/examples/schema_with_excluded_fields.py)

There was a bug in `flask_accepts` where the created Swagger doc was not respecting these parameters that has now been fixed, so thanks for bringing this to my attention.

One thing to be aware of is that in Swagger the model name is tied to the model instance, meaning you cannot refer to multiple models with the same name. Therefore, creating multiple instances of the same Schema with variations of `only`, `excludes`, etc all refer to different models, so you will need to provide them with different names (perhaps `WidgetCreate`, `Widget`..). See the example I linked.

If this is unacceptably inconvenient, there are a couple of things we could do. One would be to alter the auto-naming functionality to check for the presence of exclude fields and alter the name accordingly so that there are not collisions. A second would be to investigate whether Swagger/RESTplus has compatible parameters for reusing the same models with excluded fields, in which case an internal mapping could be established.

**Comment by apryor6** [comment]
You’ll need to pip install —upgrade flask_accepts to see the mentioned bug fix

**Comment by shawalli** [comment]
Wow, thanks for the quick response! That does exactly what I need!
