### ISSUE TITLE
Output data is not validated

### ISSUE THREAD

**Issue by elnygren** [apryor6/flask_accepts#42]
Output data is not validated which means that the generated Swagger API docs might be outdated / out of sync with the actual data returned by API.

Explanation:

`@responds` uses Marshmallow `schema.dumps` which does not validate.

https://stackoverflow.com/questions/34191547/marshmallow-not-giving-errors

**Comment by apryor6** [comment]
Validation is only applied upon parsing inputs, not validating outputs as indicated both by the SO link you posted (for Marshmallow) and [here](https://github.com/noirbizarre/flask-restplus/issues/478)(for Flask-RESTplus). I imagine this convention arises because the input parameters are coming from an external, potentially unknown or unsafe source, whereas the output data follows a known path.

Given that the intent of flask_accepts is to unify these two libraries and not necessarily enrich with additional functionality, I would consider this not an issue.

**Comment by elnygren** [comment]
@apryor6 thanks for the reply!

Btw. @responds has a "validate" param that is ignored:
https://github.com/apryor6/flask_accepts/blob/master/flask_accepts/decorators/decorators.py#L132

Could that be used to force validation on the data with `schema.validate()` ?
