### ISSUE TITLE
Nested Marshmallow Schemas throwing error on Swagger

### ISSUE THREAD

**Issue by brandondavismbo** [apryor6/flask_accepts#79]
Using the code from Issue #25 I'm seeing an error thrown in swagger.

Schemas registered with fields.Nested() are not showing up in the swagger ui, and the ui throws the error.

![image](https://user-images.githubusercontent.com/20804817/82381770-9c76a780-99df-11ea-9d4d-a5f6c7509800.png)

code: 
```
import datetime
from dataclasses import dataclass
import werkzeug
werkzeug.cached_property = werkzeug.utils.cached_property
from marshmallow import fields, Schema, post_load
from flask import Flask, jsonify, request
from flask_accepts import accepts, responds


class CogSchema(Schema):
    cog_foo = fields.String(default="cog")
    cog_baz = fields.Integer(default=999)


class WidgetSchema(Schema):
    foo = fields.String(default="test string")
    baz = fields.Integer(default=42)
    flag = fields.Bool(default=False)
    date = fields.Date(default="01-01-1900")
    dec = fields.Decimal(default=42.42)
    dct = fields.Dict(default={"key": "value"})

    cog = fields.Nested(CogSchema)


def create_app(env=None):
    from flask_restplus import Api, Namespace, Resource

    app = Flask(__name__)
    api = Api(app)

    @app.route("/simple/make_a_widget", methods=["POST"])
    @accepts(dict(name="some_arg", type=str), schema=WidgetSchema)
    @responds(schema=WidgetSchema)
    def post():
        from flask import jsonify

        return request.parsed_obj

    @api.route("/restplus/make_a_widget")
    class WidgetResource(Resource):
        @accepts(dict(name="some_arg", type=str), schema=WidgetSchema, api=api)
        @responds(schema=WidgetSchema, api=api)
        def post(self):
            from flask import jsonify

            return request.parsed_obj

    return app


app = create_app()
if __name__ == "__main__":
    app.run(debug=True)
```

**Comment by dueghis** [comment]
Hey @apryor6, any thoughts on how to fix this?

**Comment by apryor6** [comment]
Sorry for the absurd delay - things have been tremendously busy, and I totally let this slip.

This is definitely a bug. No logical reason it shouldn’t work. I hope to be able to take a look soon and determine the root cause and push out a fix; however, I’m super strapped for time between work, family, etc. If I had to guess, it’s likely a pretty small fix with one of the recursive translation functions just by looking at the nature of the bug. If somebody were to solve before I find time, I’d happily review and accept a PR. We should also add a unit test against this to prevent a regression.

**Comment by dueghis** [comment]
Hey @apryor6, we were using `flask_restplus` and weren't aware of `flask_restx`. We upgraded and the problem magically fixed itself.

**Comment by brandondavismbo** [comment]
I'm fine closing this, with upgrading to restx as a solution, unless you think the library needs full support for restplus. Thanks @dueghis !

**Comment by apryor6** [comment]
Ah, that makes sense! Definitely want to use restx these days. Bit of context: restplus is a dead project and restx is the new “official” fork. Basically the owner of restplus went off the radar, and the other contributors were stuck being unable to make new releases. After a bunch of discussion, decision was made to make a fork and since then a number of outstanding issues have been fixed, these being related to one of them.
